# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

df = spark.read.table("digital_redlining.bronze_census.raw_demographic_msa")

# COMMAND ----------

display(df)

# COMMAND ----------

import sys

sys.path.append("/Repos/digital_redlining/digital_redlining_new/gold_all")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM digital_redlining.gold_all.sample_aggregation_gold_all"))
