-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `digital_redlining`;
USE SCHEMA `census_demo`;

-- COMMAND ----------

GRANT ALL PRIVILEGES ON CATALOG digital_redlining TO `lockwood.da88@gmail.com`;
     GRANT ALL PRIVILEGES ON SCHEMA digital_redlining.census_demo TO `lockwood.da88@gmail.com`;

-- COMMAND ----------

LIST '/Volumes/digital_redlining/census_demo/src_files/';

-- COMMAND ----------

SHOW VOLUMES IN digital_redlining.census_demo;

-- COMMAND ----------

SELECT * FROM read_files(
  '/Volumes/digital_redlining/census_demo/src_files/ACSDP5Y2024.DP05-Data.csv',
  format => 'csv',
  header => true,
  mode => 'FAILFAST');
